name: AdminEssentials
version: 1.1.2
author: Jeremy Gooch (Googlelover1234)
main: adminessentials.main.Main
description: AdminEssentials is a lightweight plugin that has one goal - provide server administrators with helpful commands for advanced moderation
commands:
  admin:
    description: Staff Command.
    permission: adminessentials.admin
  clearchat:
    description: Staff Command.
    permission: adminessentials.clearchat
    aliases: [cc, cchat, clearc]
  mutechat:
    description: Staff Command.
    permission: adminessentials.mutechat
    aliases: [mc, mutec, mchat]
  playerclearchat:
    description: Staff Command.
    permission: adminessentials.playerclearchat
    aliases: [pcc, playercc, pclearchat]
  adminessentials:
    description: Staff Command.
    permission: adminessentials.reload
    aliases: [aess]

permissions:
  adminessentials.*:
    description: Gives all command permissions to AdminEssentials.
    children:
      adminessentials.admin: true
      adminessentials.clearchat: true
      adminessentials.update: true
      adminessentials.mutechat: true
      adminessentials.mutechat.bypass: true
      adminessentials.seeadmins: true
      adminessentials.playerclearchat: true
      adminessentials.help: true
      adminessentials.reload: true
  adminessentials.admin:
    description: Staff Permission.
    default: op
  adminessentials.clearchat:
    description: Staff Permission.
    default: op
  adminessentials.update:
    description: Lets you see a chat message when there is currently an update.
    default: false
  adminessentials.mutechat:
    description: Staff Permission.
    default: op
  adminessentials.mutechat.bypass:
    description: Staff Permission.
    default: op
  adminessentials.seeadmins:
    description: Staff Permission.
    default: op
  adminessentials.playerclearchat:
    description: Staff Permission.
    default: op
  adminessentials.help:
    description: Staff Permission.
    default: op
  adminessentials.reload:
    description: Staff Permission.
    default: op