name: AdminEssentials
version: 1.0.5
main: com.GummyPvP.AdminEssentials.Main.Main
description: Essential admin commands for a Minecraft server
author: Googlelover1234
commands:
  clearchat:
    description: Clear the text in the chat box.
    usage: /<command>
    aliases: [cc, cchat, clearc]
    permission: adminessentials.clearchat
  admin:
    description: Go into admin mode.
    usage: /<command>
    permission: adminessentials.admin
  mutechat:
    description: Mute the entire server, excluding players with a bypass permission.
    usage: /<command>
    aliases: [mc, mchat, mutec]
    permission: adminessentials.mutechat
  adminessentials:
    description: Main command for AdminEssentials.
    usage: /<command> [reload]
    aliases: aess
    permission: adminessentials.reload
  freeze:
    description: Freeze players in their current position.
    usage: /<command> [player]
    permission: adminessentials.freeze
  unfreeze:
    description: Unfreeze players, if they are already frozen.
    usage: /<command> [player]
    permission: adminessentials.freeze
permissions:
  adminessentials.*:
    description: Gives access to ALL AdminEssentials commands.
    default: op
    children:
      adminessentials.clearchat: true
      adminessentials.mutechat: true
      adminessentials.reload: true
      adminessentials.admin: true
      adminessentials.seeadmins: true
      adminessentials.mutechat.bypass: true
      adminessentials.freeze: true
  adminessentials.admin:
    description: Lets you go into admin mode.
    default: op
  adminessentials.reload:
    description: Lets you reload the config.
    default: op
  adminessentials.clearchat:
    description: Lets you clear the chat.
    default: op
  adminessentials.mutechat:
    description: Lets you mute the chat.
    default: op
  adminessentials.seeadmins:
    description: Lets you see people in admin mode.
    default: op
  adminessentials.mutechat.bypass:
    description: Lets you talk when chat is muted.
    default: op
  adminessentials.freeze:
    description: Lets you use the freeze and unfreeze command.
    default: op
